# Generated by Django 4.2.27 on 2025-12-26 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
