# Generated by Django 5.2.7 on 2025-12-27 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0002_learningcontent_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('priority', models.IntegerField(default=0)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='LearningAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('learning_path_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Learning Path', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('unlocked', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='LearningScenario',
        ),
        migrations.AlterModelOptions(
            name='learningcontent',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='usercontentprogress',
            options={'verbose_name_plural': 'User content progress'},
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='avg_completion_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium Easy'), (4, 'Medium'), (5, 'Medium Hard'), (6, 'Hard'), (7, 'Very Hard'), (8, 'Expert'), (9, 'Master'), (10, 'Genius')], default=4),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='estimated_time_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='leads_to', to='adaptive_learning.learningcontent'),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='success_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usercontentprogress',
            name='difficulty_feedback',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium Easy'), (4, 'Medium'), (5, 'Medium Hard'), (6, 'Hard'), (7, 'Very Hard'), (8, 'Expert'), (9, 'Master'), (10, 'Genius')], null=True),
        ),
        migrations.AddField(
            model_name='usercontentprogress',
            name='interactions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usercontentprogress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercontentprogress',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usercontentprogress',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontentprogress',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('scenario', 'Scenario'), ('interactive', 'Interactive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='max_level',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium Easy'), (4, 'Medium'), (5, 'Medium Hard'), (6, 'Hard'), (7, 'Very Hard'), (8, 'Expert'), (9, 'Master'), (10, 'Genius')], default=10),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='min_level',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium Easy'), (4, 'Medium'), (5, 'Medium Hard'), (6, 'Hard'), (7, 'Very Hard'), (8, 'Expert'), (9, 'Master'), (10, 'Genius')], default=1),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.learningcontent'),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learninganalytics',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.learningcontent'),
        ),
        migrations.AddField(
            model_name='learninganalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='current_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_paths', to='adaptive_learning.learningcontent'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningpathitem',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.learningcontent'),
        ),
        migrations.AddField(
            model_name='learningpathitem',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.learningpath'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='contents',
            field=models.ManyToManyField(related_name='learning_paths', through='adaptive_learning.LearningPathItem', to='adaptive_learning.learningcontent'),
        ),
        migrations.AddIndex(
            model_name='learninganalytics',
            index=models.Index(fields=['user', 'timestamp'], name='adaptive_le_user_id_7ec92f_idx'),
        ),
        migrations.AddIndex(
            model_name='learninganalytics',
            index=models.Index(fields=['event_type', 'timestamp'], name='adaptive_le_event_t_827c45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningpathitem',
            unique_together={('learning_path', 'content')},
        ),
    ]
