# Generated by Django 5.2.7 on 2026-01-01 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0004_alter_contentrecommendation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningpathitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learninganalytics',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adaptive_learning.learningcontent'),
        ),
        migrations.AddField(
            model_name='usercontentprogress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercontentprogress',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contentrecommendation',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='name',
            field=models.CharField(default='My Learning Path', max_length=255),
        ),
        migrations.AlterField(
            model_name='learningpathitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learningpathitem',
            name='unlocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='learningpathitem',
            unique_together={('learning_path', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='usercontentprogress',
            unique_together={('user', 'content')},
        ),
    ]
