# Generated by Django 5.2.7 on 2026-01-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0005_alter_learningpathitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningpathitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='learningpathitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usercontentprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contentrecommendation',
            name='clicked',
        ),
        migrations.RemoveField(
            model_name='learninganalytics',
            name='content',
        ),
        migrations.AlterField(
            model_name='contentrecommendation',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('scenario', 'Scenario')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='difficulty',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='learningpathitem',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='learningpathitem',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='usercontentprogress',
            name='time_spent_seconds',
        ),
    ]
