# Generated by Django 5.2.7 on 2026-01-05 18:21

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', builtins.id]},
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('test', 'order'), name='unique_question_order_per_test'),
        ),
    ]
