# Generated by Django 5.2.7 on 2025-12-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='score',
        ),
    ]
