# Generated by Django 4.2.27 on 2025-12-26 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adaptive_learning', '0002_learningcontent_created_at_and_more'),
        ('assessment', '0002_remove_choice_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cognitivetest',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='answer',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='زمان صرف شده برای پاسخ (ثانیه)'),
        ),
        migrations.AddField(
            model_name='cognitivetest',
            name='passing_score',
            field=models.IntegerField(default=70, help_text='حداقل نمره قبولی (درصد)'),
        ),
        migrations.AddField(
            model_name='cognitivetest',
            name='related_content',
            field=models.ForeignKey(blank=True, help_text='محتوای آموزشی مرتبط', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adaptive_learning.learningcontent'),
        ),
        migrations.AddField(
            model_name='cognitivetest',
            name='time_limit_minutes',
            field=models.IntegerField(default=60, help_text='مدت زمان آزمون (دقیقه)'),
        ),
        migrations.AddField(
            model_name='cognitivetest',
            name='total_questions',
            field=models.IntegerField(default=10, help_text='تعداد سوالات آزمون'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=10, help_text='امتیاز این سوال'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsession',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('timeout', 'اتمام زمان')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='testsession',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ContentTestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.learningcontent')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.cognitivetest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content', 'test')},
            },
        ),
    ]
