# Generated by Django 5.2.7 on 2025-12-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_cognitivetest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitivetest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cognitivetest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
