# Generated by Django 5.2.7 on 2025-12-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_question_explanation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='زمان صرف شده در کل آزمون (ثانیه)'),
        ),
    ]
