# Generated by Django 5.2.7 on 2026-06-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'شهروند'), ('teacher', 'مسئول شهری (مدرس)'), ('admin', 'مدیر سیستم')], default='student', max_length=20),
        ),
    ]
