# Generated by Django 5.2.7 on 2026-07-27 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='levelhistory',
            name='test_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.testsession'),
        ),
        migrations.AddField(
            model_name='levelhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userperformancesummary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_summary', to=settings.AUTH_USER_MODEL),
        ),
    ]
